export interface ITicket {

    EnquiryId: number,
    CustomerId: number,
    CustomerName: string,
    ContactNo: number,
    Email: any,
    EnquieryDate: any,
    Description: any,
    StatusId: number,
    StatusName: string,
    StatusNameAr: string,
    Subject: string,
    AssignedTo: string,
    PriorityId: number,
    PriorityName: string,
    PriorityNameAr: string,
    GroupId: number,
    GroupName: string,
    GroupNameAr: string,
    SubGroupId: number,
    SubGroupName: string,
    SubGroupNameAr: string,
    TicketTypeId: number,
    TicketTypeName: string,
    TicketTypeNameAr: string,
    TicketAssignGroupId: number,
    TicketAssignGroupName: string,
    TicketAssignGroupNameAr: string,
    TicketCreater: string,
    ContractNumber: any,
    LabourNumber: null,
    LabourName: null,
    TicketChannelId: 7,
    TicketChannelName: string,
    TicketChannelNameAr: null,
    IsClosed: false,
    EnqFiles: [],
    PriorityOrder: number,
    ModifiedDatetime: any,
    RecVersion: null,
    CreatedBy: string,
    ModifyBy: string,
    CreatedDatetime: any,
    Accuracy: null,
    RecId: null

}